# Generated by Django 3.2 on 2023-01-17 01:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('descripcion', models.CharField(max_length=150)),
                ('imagen_Album', models.ImageField(upload_to='caratula')),
            ],
        ),
        migrations.CreateModel(
            name='fotoAlbum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='fotos')),
                ('fotos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyectos.album')),
            ],
        ),
    ]
