# Generated by Django 3.2 on 2023-01-17 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='descripcion',
            field=models.TextField(max_length=150),
        ),
    ]
